name: dev deploy

on:
  push:
    tags:
      - v*

jobs:
  release-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Wait test to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'release-deploy'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Wait build to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'release-deploy'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Write secrets to file
        run: |
          echo ossrh.username=${{ secrets.MAVEN_USERNAME }} > local.properties
          echo ossrh.password=${{ secrets.MAVEN_PASSWD }} >> local.properties
          echo signing.key=${{ secrets.SIGNING_KEY }} >> local.properties
          echo signing.password=${{ secrets.SIGNING_PASSWD }} >> local.properties

      - name: Publish to snapshot repository
        env:
          RELEASE: 1
        run: ./gradlew publishToSonatype
